#!/usr/bin/env node
/**
 * Copies the front-end CV from its source project into the site: the text /cv renders, and the PDF
 * it serves.
 *
 *   CV_DIR=<path to the cv folder> node scripts/sync-cv.mjs
 *
 * Build the CV there first. The PDF is that project's own print with the phone number taken out:
 * this repo is public, and the site's contact rule is email and LinkedIn only.
 */

import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const VARIANT = '01-frontend';
const SITE = join(dirname(fileURLToPath(import.meta.url)), '..');
const CV_DIR = process.env.CV_DIR;
if (!CV_DIR) throw new Error('Set CV_DIR to the cv folder of the CV project.');

const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));
const dataPath = join(CV_DIR, 'data.json');
const contentPath = join(CV_DIR, 'content', `${VARIANT}.json`);
const htmlPath = join(CV_DIR, 'dist', `${VARIANT}.html`);

const printed = statSync(htmlPath).mtimeMs;
if ([dataPath, contentPath].some((path) => statSync(path).mtimeMs > printed)) {
  throw new Error(`${htmlPath} is older than its sources. Build the CV first.`);
}

const data = readJson(dataPath);
const content = readJson(contentPath);

const cv = {
  $comment: `Generated by scripts/sync-cv.mjs from the CV project, cv/${VARIANT}. Edit there, then sync.`,
  name: data.name,
  headline: content.headline,
  summary: content.summary,
  availability: content.availability,
  location: data.location,
  email: data.email,
  linkedin: data.linkedin,
  skills: content.skills,
  roles: data.roles
    .filter((role) => content.roles[role.id])
    .map((role) => ({ ...role, bullets: content.roles[role.id] })),
  projects: content.projects
    .map((id) => data.projects.find((project) => project.id === id))
    .filter(Boolean),
  education: data.education,
  languages: data.languages,
};

// Checked as bare digits, so no spacing or formatting of the number gets past.
const digits = data.phone.replace(/\D/g, '');
const leaks = (text) => text.replace(/\D/g, '').includes(digits) || text.includes('tel:');

const json = JSON.stringify(cv, null, 2);
if (leaks(json)) throw new Error('phone number reached cv.json');
writeFileSync(join(SITE, 'src', 'data', 'cv.json'), `${json}\n`);

const html = readFileSync(htmlPath, 'utf8').replace(`<span>${data.phone}</span>`, '');
if (leaks(html)) throw new Error(`phone number still in ${htmlPath}`);

const { findChrome, printPdf } = await import(pathToFileURL(join(CV_DIR, 'chrome.mjs')).href);
const tmp = mkdtempSync(join(tmpdir(), 'cv-'));
try {
  const page = join(tmp, `${VARIANT}.html`);
  writeFileSync(page, html);
  const pdf = join(SITE, 'public', 'amir-balazade-cv.pdf');
  printPdf(findChrome(), page, pdf);
  console.log(`cv.json and amir-balazade-cv.pdf (${Math.round(statSync(pdf).size / 1024)} KB)`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
